### ISSUE TITLE
problem after installation

### ISSUE THREAD

**Issue by mpawlak12** [ChristianGrieger/Cryptocurrency-faucet-script#7]
Can u help me repair this error 
http://screenshot.sh/ofpxd90iSjPqk

Thanks

**Comment by ChristianGrieger** [comment]
Sorry but it looks like your link does not work anymore.

**Comment by BlasiniBitCoin** [comment]
![image](https://user-images.githubusercontent.com/29293055/26956495-294dd830-4c8c-11e7-88ee-ccecbe5a3454.png)
:/ what happen with that no work anymore ?

**Comment by ChristianGrieger** [comment]
I am sure it still works but i dont work on it anymore sorry.
