### ISSUE TITLE
Specific account not used in 'getbalance'

### ISSUE THREAD

**Issue by xcoinproject** [ChristianGrieger/Cryptocurrency-faucet-script#9]
When specifying "stage_payment_account_name" => "account" I expected that account to be used to bring back the faucet balance.

Instead the entire balance of the wallet is returned for the faucet balance.

simple_faucet.php:
$this->balance = $this->rpc("getbalance")

I have tried modifying it to $this->balance = $this->rpc("getbalance account") without success.
I have also tried $this->balance = $this->rpc("getbalance $config["stage_payment_account_name"]")

How can this code be modified to bring back the balance of only the account specified?

When using the bitcoin cli interface, "getbalance" returns the entire wallet balance and "getbalance account" returns the balance of "account" within the wallet. This isn't the same behaviour when changing the above code - I'm not sure what I'm doing wrong.

**Comment by ChristianGrieger** [comment]
I am sorry but I did not use the code for years. You will have to figure it out.

**Comment by cryptopool-builders** [comment]
I  know this is closed but didnt see a answer, the correct way to do this is 

`if (!mysqli_connect_error() && !is_null($this->balance = $this->rpc("getbalance", array("ACCOUNTNAME") ))) // compatibility with older PHP versions`
